class Repo(
            archive_url : String,
            archived : Boolean,
            assignees_url : String,
            blobs_url : String,
            branches_url : String,
            clone_url : String,
            collaborators_url : String,
            comments_url : String,
            commits_url : String,
            compare_url : String,
            contents_url : String,
            contributors_url : String,
            created_at : String,
            default_branch : String,
            deployments_url : String,
            description : String,
            downloads_url : String,
            events_url : String,
            fork : Boolean,
            forks : Long,
            forks_count : Long,
            forks_url : String,
            full_name : String,
            git_commits : String,
            git_refs_url : String,
            git_tags_url : String,
            git_url  : String,
            has_downloads : Boolean,
            has_issues : Boolean,
            has_pages : Boolean,
            has_projects : Boolean,
            has_wiki : Boolean,
            homepage : String,
            hooks_url : String,
            html_url : String,
            id : Long,
            issue_comment_url : String,
            issue_events_url : String,
            issues_url : String,
            keys_url : String,
            labels_url : String,
            language : String,
            languages_url : String
          ) extends Product with Serializable {

}
